spring:
  profiles:
    active: local
  batch:
    job:
      enabled: false

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: orgr.h2.Driver

---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=Asia/Seoul #db url과 정확히 일치하도록 작성
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
